# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2026 tcr-cliff contributors
"""Downloaders for real public TCR-pMHC datasets, normalised to the canonical schema.

Each loader documents its **real public source URL** (see the module constants
:data:`VDJDB_URL`, :data:`MCPAS_URL`, :data:`IEDB_URL`, :data:`NETTCR_URL`),
downloads the raw table to a cache directory (default ``~/.cache/tcr_cliff`` or
``C:\\tcrtmp`` on Windows), parses it, and maps its columns onto the canonical
schema defined in :mod:`tcr_cliff.data.schema`.

This module **never fabricates rows**. If a download or parse fails for any reason
(network, format drift, licence wall) the loader raises :class:`RuntimeError`
pointing the user at ``DATASETS.md`` for manual-download instructions.

See ``DATASETS.md`` for the URL, licence, and citation of every source, and for an
explicit statement that the *bundled toy set is synthetic* (generated by
:mod:`tcr_cliff.data.toy._generate`) and must not be used for benchmark claims.
"""

from __future__ import annotations

import io
import os
import urllib.error
import urllib.request
import zipfile
from pathlib import Path

import pandas as pd

from tcr_cliff._logging import get_logger
from tcr_cliff.data.schema import ALL_COLUMNS, clean_sequence, validate_pairs

_log = get_logger("data.download")

# --------------------------------------------------------------------------- #
# Real public source URLs. These are the canonical, citeable download endpoints.
# They are NOT fetched during the build/test task; see DATASETS.md for details.
# --------------------------------------------------------------------------- #

#: VDJdb release pointer. ``latest-version.txt`` lists release ZIP URLs (newest
#: first); each ZIP contains ``vdjdb.slim.txt``. https://vdjdb.cdr3.net
VDJDB_URL = "https://raw.githubusercontent.com/antigenomics/vdjdb-db/master/latest-version.txt"

#: McPAS-TCR full database export (human + mouse). https://friedmanlab.weizmann.ac.il/McPAS-TCR/
#: The site migrated to an R/Shiny app; the old ``/Download/McPAS-TCR.csv`` path now
#: 404s, but the CSV is still served statically at the app root (this URL).
MCPAS_URL = "https://friedmanlab.weizmann.ac.il/McPAS-TCR/McPAS-TCR.csv"

#: IEDB receptor/TCR export portal. Programmatic CSV export from the T cell receptor table.
IEDB_URL = "https://www.iedb.org/downloader.php?file_name=doc/receptor_full_v3.zip"

#: NetTCR-2.0 / ImmRep training+test data (Montemurro et al. 2021).
NETTCR_URL = "https://raw.githubusercontent.com/mnielLab/NetTCR-2.0/main/data/train_beta_90.csv"

#: NetTCR-2.0 input column order (CDR3-beta + peptide + binder label).
NETTCR_COLUMNS: tuple[str, ...] = ("CDR3b", "peptide", "binder")

_DATASETS_HINT = (
    "See DATASETS.md for the source URL, licence, and manual-download "
    "instructions (place the file in the cache dir and re-run)."
)


# --------------------------------------------------------------------------- #
# Cache / download helpers
# --------------------------------------------------------------------------- #


def default_cache_dir() -> Path:
    """Return the default on-disk cache directory for downloaded datasets.

    Returns
    -------
    pathlib.Path
        ``~/.cache/tcr_cliff`` on POSIX, or ``C:\\tcrtmp`` on Windows. The
        directory is *not* created here; callers create it on demand.
    """
    if os.name == "nt":
        return Path(r"C:\tcrtmp")
    return Path.home() / ".cache" / "tcr_cliff"


def _resolve_cache_dir(cache_dir: str | Path | None) -> Path:
    """Resolve and create the cache directory for a download."""
    base = Path(cache_dir) if cache_dir is not None else default_cache_dir()
    base.mkdir(parents=True, exist_ok=True)
    return base


def _download(url: str, dest: Path, *, timeout: float = 60.0) -> Path:
    """Download ``url`` to ``dest`` (cached), returning the local path.

    Parameters
    ----------
    url:
        The remote source URL.
    dest:
        Local destination path. If it already exists it is returned unchanged
        (the cache hit), so repeated loads do not re-fetch.
    timeout:
        Socket timeout in seconds.

    Raises
    ------
    RuntimeError
        If the download fails for any reason. The message points at
        ``DATASETS.md`` so the user can fetch the file manually.
    """
    if dest.exists() and dest.stat().st_size > 0:
        _log.info("cache hit: %s", dest)
        return dest
    _log.info("downloading %s -> %s", url, dest)
    try:
        req = urllib.request.Request(url, headers={"User-Agent": "tcr-cliff/0.1"})
        with urllib.request.urlopen(req, timeout=timeout) as resp:
            data = resp.read()
        dest.write_bytes(data)
    except (urllib.error.URLError, OSError, ValueError) as exc:
        raise RuntimeError(
            f"Failed to download {url!r} to {dest}: {exc}. {_DATASETS_HINT}"
        ) from exc
    if dest.stat().st_size == 0:
        raise RuntimeError(f"Downloaded empty file from {url!r}. {_DATASETS_HINT}")
    return dest


def _read_table(path: Path, *, sep: str = "\t") -> pd.DataFrame:
    """Read a cached delimited table (utf-8 then latin-1), raising a pointed error."""
    last: Exception | None = None
    # utf-8-sig strips a BOM (McPAS ships one); latin-1 is the last-resort fallback.
    for enc in ("utf-8-sig", "latin-1"):
        try:
            return pd.read_csv(path, sep=sep, low_memory=False, encoding=enc)
        except UnicodeDecodeError as exc:  # try the next encoding
            last = exc
            continue
        except Exception as exc:
            raise RuntimeError(f"Failed to parse {path}: {exc}. {_DATASETS_HINT}") from exc
    raise RuntimeError(f"Failed to parse {path}: {last}. {_DATASETS_HINT}")


def _flatten_iedb_header(top: object, sub: object) -> str:
    """Flatten an IEDB two-row header cell to ``"Group - Field"``.

    Keeping the group prefix is essential: the alpha (``Chain 1``) and beta
    (``Chain 2``) CDR3 columns share the field name ``CDR3 Curated`` and would
    otherwise collide into a single ambiguous column.
    """
    top, sub = str(top), str(sub)
    if "Unnamed" in sub:
        return top.strip()
    if "Unnamed" in top:
        return sub.strip()
    return f"{top} - {sub}".strip()


def _finalize(df: pd.DataFrame, source: str) -> pd.DataFrame:
    """Tag the source column and validate against the canonical schema.

    Parameters
    ----------
    df:
        A frame already carrying (at least) the required canonical columns.
    source:
        The source tag written into the ``source`` column.

    Raises
    ------
    RuntimeError
        If validation fails (e.g. no valid rows survived normalisation).
    """
    if df.empty:
        raise RuntimeError(f"{source} produced no rows after column mapping. {_DATASETS_HINT}")
    df = df.copy()
    df["source"] = source
    try:
        return validate_pairs(df)
    except Exception as exc:
        raise RuntimeError(
            f"{source} rows failed schema validation: {exc}. {_DATASETS_HINT}"
        ) from exc


def _first_present(df: pd.DataFrame, candidates: tuple[str, ...]) -> str | None:
    """Return the first column name in ``candidates`` that exists in ``df``."""
    lower = {c.lower(): c for c in df.columns}
    for cand in candidates:
        if cand in df.columns:
            return cand
        if cand.lower() in lower:
            return lower[cand.lower()]
    return None


# --------------------------------------------------------------------------- #
# Public loaders
# --------------------------------------------------------------------------- #


def load_vdjdb(cache_dir: str | Path | None = None) -> pd.DataFrame:
    """Download and load VDJdb, mapped to the canonical schema.

    Source
    ------
    VDJdb full export (``latest-version.txt``), a tab-separated table of curated
    TCR-epitope specificity records: :data:`VDJDB_URL`.

    Parameters
    ----------
    cache_dir:
        Directory to cache the raw download. Defaults to
        :func:`default_cache_dir`.

    Returns
    -------
    pandas.DataFrame
        Canonical-schema pairs frame (binder defaults to 1: VDJdb lists positive
        specificities only).

    Raises
    ------
    RuntimeError
        On any download/parse/mapping failure; the message points at
        ``DATASETS.md``.
    """
    cache = _resolve_cache_dir(cache_dir)
    # 'latest-version.txt' lists release ZIP URLs (newest first); follow the first.
    ver_path = _download(VDJDB_URL, cache / "vdjdb_latest.txt")
    urls = [ln.strip() for ln in ver_path.read_text().splitlines() if ln.strip().startswith("http")]
    if not urls:
        raise RuntimeError(f"VDJdb latest-version.txt had no release URL. {_DATASETS_HINT}")
    zip_path = _download(urls[0], cache / Path(urls[0]).name)
    try:
        with zipfile.ZipFile(zip_path) as zf:
            members = [n for n in zf.namelist() if n.endswith("vdjdb.slim.txt")] or [
                n for n in zf.namelist() if n.endswith("vdjdb.txt")
            ]
            if not members:
                raise RuntimeError(f"No vdjdb table inside {zip_path}. {_DATASETS_HINT}")
            with zf.open(members[0]) as fh:
                raw = pd.read_csv(fh, sep="\t", low_memory=False)
    except zipfile.BadZipFile as exc:
        raise RuntimeError(f"VDJdb release not a valid ZIP: {exc}. {_DATASETS_HINT}") from exc

    cdr3 = _first_present(raw, ("cdr3", "CDR3", "cdr3b", "CDR3.beta"))
    pep = _first_present(raw, ("antigen.epitope", "Epitope", "antigen", "peptide"))
    gene = _first_present(raw, ("gene", "Gene"))
    if cdr3 is None or pep is None:
        raise RuntimeError(
            f"VDJdb columns not recognised (have {list(raw.columns)[:12]}...). " f"{_DATASETS_HINT}"
        )

    # VDJdb mixes TRA/TRB; keep beta chains when a gene column is present.
    if gene is not None:
        raw = raw.loc[raw[gene].astype(str).str.upper().str.contains("TRB", na=False)]

    mhc = _first_present(raw, ("mhc.a", "MHC A", "mhc_a"))
    vg = _first_present(raw, ("v.segm", "V", "v_gene"))
    jg = _first_present(raw, ("j.segm", "J", "j_gene"))

    out = pd.DataFrame(
        {
            "cdr3b": raw[cdr3].map(clean_sequence),
            "peptide": raw[pep].map(clean_sequence),
            "binder": 1,
        }
    )
    out["mhc"] = raw[mhc].astype(str).values if mhc else ""
    out["v_gene"] = raw[vg].astype(str).values if vg else ""
    out["j_gene"] = raw[jg].astype(str).values if jg else ""
    out["pair_id"] = [f"vdjdb{i:06d}" for i in range(len(out))]
    return _finalize(out, "vdjdb")


def load_mcpas(cache_dir: str | Path | None = None) -> pd.DataFrame:
    """Download and load McPAS-TCR, mapped to the canonical schema.

    Source
    ------
    McPAS-TCR full database CSV (Tickotsky et al. 2017): :data:`MCPAS_URL`.

    Parameters
    ----------
    cache_dir:
        Directory to cache the raw download. Defaults to
        :func:`default_cache_dir`.

    Returns
    -------
    pandas.DataFrame
        Canonical-schema pairs frame (binder=1; McPAS lists associations only).

    Raises
    ------
    RuntimeError
        On any download/parse/mapping failure; the message points at
        ``DATASETS.md``.
    """
    cache = _resolve_cache_dir(cache_dir)
    dest = cache / "McPAS-TCR.csv"
    if not (dest.exists() and dest.stat().st_size > 0):
        _download(MCPAS_URL, dest)
    # Defensive: if the app moves again and the URL 404s to an HTML page, detect that
    # and point the user at the manual-download fallback rather than parsing HTML.
    if dest.read_bytes()[:64].lstrip()[:1] == b"<":
        dest.unlink(missing_ok=True)
        raise RuntimeError(
            "McPAS-TCR returned HTML, not CSV (the app URL may have moved again). "
            "Download 'McPAS-TCR.csv' manually from "
            f"https://friedmanlab.weizmann.ac.il/McPAS-TCR/ and place it at {dest}, then "
            f"re-run. {_DATASETS_HINT}"
        )
    raw = _read_table(dest, sep=",")

    cdr3 = _first_present(raw, ("CDR3.beta.aa", "CDR3b", "CDR3.beta", "cdr3b"))
    pep = _first_present(raw, ("Epitope.peptide", "Epitope", "peptide"))
    if cdr3 is None or pep is None:
        raise RuntimeError(
            f"McPAS columns not recognised (have {list(raw.columns)[:12]}...). " f"{_DATASETS_HINT}"
        )

    mhc = _first_present(raw, ("MHC", "HLA"))
    vg = _first_present(raw, ("TRBV", "V"))
    jg = _first_present(raw, ("TRBJ", "J"))

    out = pd.DataFrame(
        {
            "cdr3b": raw[cdr3].map(clean_sequence),
            "peptide": raw[pep].map(clean_sequence),
            "binder": 1,
        }
    )
    out["mhc"] = raw[mhc].astype(str).values if mhc else ""
    out["v_gene"] = raw[vg].astype(str).values if vg else ""
    out["j_gene"] = raw[jg].astype(str).values if jg else ""
    out["pair_id"] = [f"mcpas{i:06d}" for i in range(len(out))]
    return _finalize(out, "mcpas")


def load_iedb(cache_dir: str | Path | None = None) -> pd.DataFrame:
    """Download and load the IEDB TCR receptor export, mapped to the schema.

    Source
    ------
    IEDB receptor (TCR) full export: :data:`IEDB_URL`. IEDB serves a ZIP; the
    CSV inside it is parsed.

    Parameters
    ----------
    cache_dir:
        Directory to cache the raw download. Defaults to
        :func:`default_cache_dir`.

    Returns
    -------
    pandas.DataFrame
        Canonical-schema pairs frame.

    Raises
    ------
    RuntimeError
        On any download/parse/mapping failure; the message points at
        ``DATASETS.md``.
    """
    cache = _resolve_cache_dir(cache_dir)
    path = _download(IEDB_URL, cache / "iedb_receptor_full_v3.zip")
    try:
        with zipfile.ZipFile(path) as zf:
            members = [n for n in zf.namelist() if n.lower().endswith(".csv")]
            if not members:
                raise RuntimeError(f"No CSV inside IEDB archive {path}. {_DATASETS_HINT}")
            with zf.open(members[0]) as fh:
                raw = pd.read_csv(io.BytesIO(fh.read()), low_memory=False, header=[0, 1])
        # IEDB uses a two-row (group, field) header; keep the group to disambiguate the
        # alpha (Chain 1) and beta (Chain 2) CDR3 columns.
        raw.columns = [_flatten_iedb_header(a, b) for a, b in raw.columns]
    except RuntimeError:
        raise
    except Exception as exc:
        raise RuntimeError(f"Failed to read IEDB archive {path}: {exc}. {_DATASETS_HINT}") from exc

    # The TCR beta chain is "Chain 2"; the epitope sequence lives in "Epitope - Name".
    cdr3 = _first_present(
        raw, ("Chain 2 - CDR3 Curated", "Chain 2 - CDR3 Calculated", "Chain 2 CDR3 Curated")
    )
    pep = _first_present(raw, ("Epitope - Name", "Epitope - Description", "Description", "Epitope"))
    if cdr3 is None or pep is None:
        raise RuntimeError(
            f"IEDB columns not recognised (have {list(raw.columns)[:12]}...). " f"{_DATASETS_HINT}"
        )
    mhc = _first_present(raw, ("Assay - MHC Allele Names", "MHC Allele Names", "MHC", "HLA"))

    out = pd.DataFrame(
        {
            "cdr3b": raw[cdr3].map(clean_sequence),
            "peptide": raw[pep].map(clean_sequence),
            "binder": 1,
        }
    )
    out["mhc"] = raw[mhc].astype(str).values if mhc else ""
    out["pair_id"] = [f"iedb{i:06d}" for i in range(len(out))]
    return _finalize(out, "iedb")


def load_nettcr(cache_dir: str | Path | None = None) -> pd.DataFrame:
    """Download and load the NetTCR-2.0 / ImmRep dataset, mapped to the schema.

    Source
    ------
    NetTCR-2.0 training data (Montemurro et al. 2021): :data:`NETTCR_URL`. This
    is the dataset whose ``CDR3b, peptide, binder`` layout :func:`to_nettcr_format`
    targets. Unlike VDJdb/McPAS/IEDB it carries explicit negative (binder=0) rows.

    Parameters
    ----------
    cache_dir:
        Directory to cache the raw download. Defaults to
        :func:`default_cache_dir`.

    Returns
    -------
    pandas.DataFrame
        Canonical-schema pairs frame with real 0/1 binder labels.

    Raises
    ------
    RuntimeError
        On any download/parse/mapping failure; the message points at
        ``DATASETS.md``.
    """
    cache = _resolve_cache_dir(cache_dir)
    path = _download(NETTCR_URL, cache / "nettcr_train_beta.csv")
    raw = _read_table(path, sep=",")

    cdr3 = _first_present(raw, ("CDR3b", "cdr3b", "CDR3", "cdr3"))
    pep = _first_present(raw, ("peptide", "Peptide", "epitope"))
    label = _first_present(raw, ("binder", "label", "y"))
    if cdr3 is None or pep is None:
        raise RuntimeError(
            f"NetTCR columns not recognised (have {list(raw.columns)[:12]}...). "
            f"{_DATASETS_HINT}"
        )

    out = pd.DataFrame(
        {
            "cdr3b": raw[cdr3].map(clean_sequence),
            "peptide": raw[pep].map(clean_sequence),
        }
    )
    out["binder"] = raw[label].astype("float").round().astype("int") if label else 1
    out["pair_id"] = [f"nettcr{i:06d}" for i in range(len(out))]
    return _finalize(out, "nettcr")


# --------------------------------------------------------------------------- #
# Interop helpers
# --------------------------------------------------------------------------- #


def to_nettcr_format(df: pd.DataFrame) -> pd.DataFrame:
    """Convert a canonical-schema frame into NetTCR-2.0 input columns.

    NetTCR-2.0 consumes a CSV with at least ``CDR3b``, ``peptide`` and a
    ``binder`` label column (see :data:`NETTCR_COLUMNS`).

    Parameters
    ----------
    df:
        Any canonical-schema pairs frame (e.g. ``load_toy()``). It is validated
        first so callers cannot accidentally pass a malformed table.

    Returns
    -------
    pandas.DataFrame
        Columns ``CDR3b, peptide, binder`` (plus ``MHC`` when ``mhc`` is present
        and non-empty).
    """
    norm = validate_pairs(df)
    out = pd.DataFrame(
        {
            "CDR3b": norm["cdr3b"].astype(str),
            "peptide": norm["peptide"].astype(str),
            "binder": norm["binder"].astype(int),
        }
    )
    if "mhc" in norm.columns and norm["mhc"].astype(str).str.len().gt(0).any():
        out["MHC"] = norm["mhc"].astype(str)
    return out


def write_nettcr_csv(df: pd.DataFrame, path: str | Path) -> Path:
    """Write a canonical frame to a NetTCR-2.0 input CSV.

    Parameters
    ----------
    df:
        Canonical-schema pairs frame.
    path:
        Destination CSV path; parent directories are created as needed.

    Returns
    -------
    pathlib.Path
        The path written.
    """
    dest = Path(path)
    dest.parent.mkdir(parents=True, exist_ok=True)
    to_nettcr_format(df).to_csv(dest, index=False)
    _log.info("wrote NetTCR-format CSV: %s", dest)
    return dest


def cdr3_from_anarci(sequence: str, scheme: str = "imgt") -> str | None:
    """Extract the CDR3 loop from a full TCR-beta variable sequence via ANARCI.

    Parameters
    ----------
    sequence:
        A full TCR variable-domain amino-acid sequence.
    scheme:
        Numbering scheme passed to ANARCI (default ``"imgt"``). Under IMGT the
        CDR3 spans positions 105-117 inclusive.

    Returns
    -------
    str or None
        The CDR3 substring, or ``None`` if ANARCI cannot number the sequence.

    Raises
    ------
    ImportError
        If ``anarci`` is not installed. Install it with
        ``pip install 'tcr-cliff[full]'`` (ANARCI is distributed via Bioconda).
    """
    try:
        from anarci import anarci as _anarci  # type: ignore[import-not-found]
    except ImportError as exc:  # pragma: no cover - exercised only without anarci
        raise ImportError(
            "cdr3_from_anarci requires the 'anarci' package, which is not "
            "installed. Install it via Bioconda (conda install -c bioconda anarci) "
            "or 'pip install ANARCI'."
        ) from exc

    seq = clean_sequence(sequence)
    if not seq:
        return None
    numbering, _details, _hits = _anarci([("query", seq)], scheme=scheme, output=False)
    if not numbering or numbering[0] is None:
        return None
    # numbering[0] is a list of domains; take the first domain's numbered list.
    domain = numbering[0][0][0]
    cdr3 = [aa for (pos, _ins), aa in domain if 105 <= pos <= 117 and aa != "-"]
    seq_out = "".join(cdr3)
    return seq_out or None


__all__ = [
    "ALL_COLUMNS",
    "IEDB_URL",
    "MCPAS_URL",
    "NETTCR_COLUMNS",
    "NETTCR_URL",
    "VDJDB_URL",
    "cdr3_from_anarci",
    "default_cache_dir",
    "load_iedb",
    "load_mcpas",
    "load_nettcr",
    "load_vdjdb",
    "to_nettcr_format",
    "write_nettcr_csv",
]
